// ============================================================
// STRINGS — the Japanese and German pages set window.HAKO_STRINGS
// (generated by tools/build-i18n.py); English is the fallback.
// ============================================================
function T(key, fallback, vars) {
  let text = (window.HAKO_STRINGS && window.HAKO_STRINGS[key]) || fallback;
  if (vars) for (const k in vars) text = text.split(`{${k}}`).join(vars[k]);
  return text;
}

// ============================================================
// ACCESS GATE — hype gate (NOT real security).
// Runs first so the page is covered before anything else renders.
//
// Password stored only as a SHA-256 hash, so source-viewing won't
// reveal the phrase. A determined dev can still bypass via DevTools
// (inherent limit of client-side gating), but can't learn the phrase.
//
// To change the password, run in any browser console:
//   crypto.subtle.digest("SHA-256", new TextEncoder().encode("yourphrase"))
//     .then(b => console.log([...new Uint8Array(b)]
//       .map(x => x.toString(16).padStart(2,"0")).join("")));
// then paste the result as GATE_HASH below.
// ============================================================
(function() {
  const GATE_HASH =
    "9084bb947c414a201d727de0982159afccff5b614f8566c1b51f0ebf610aab8a"; // hako2027
  const STORAGE_KEY = "hako-gate-ok";

  const gate = document.getElementById("accessGate");
  if (!gate) return;

  if (sessionStorage.getItem(STORAGE_KEY) === "1") {
    gate.parentNode && gate.parentNode.removeChild(gate);
    return;
  }

  document.body.classList.add("gate-locked");

  const form = document.getElementById("gateForm");
  const input = document.getElementById("gateInput");
  const errorEl = document.getElementById("gateError");

  async function sha256Hex(text) {
    const buf = await crypto.subtle.digest(
      "SHA-256",
      new TextEncoder().encode(text)
    );
    return [...new Uint8Array(buf)]
      .map((b) => b.toString(16).padStart(2, "0"))
      .join("");
  }

  function unlock() {
    sessionStorage.setItem(STORAGE_KEY, "1");
    document.body.classList.remove("gate-locked");
    gate.classList.add("gate-hidden");
    setTimeout(() => {
      gate.parentNode && gate.parentNode.removeChild(gate);
    }, 750);
  }

  function reject() {
    if (errorEl) {
      errorEl.textContent = T("gate.wrong", "Not quite. Check the Discord for the phrase.");
      errorEl.classList.add("show");
    }
    if (form) {
      form.classList.add("gate-shake");
      setTimeout(() => form.classList.remove("gate-shake"), 450);
    }
    if (input) {
      input.value = "";
      input.focus();
    }
  }

  if (form) {
    form.addEventListener("submit", async (e) => {
      e.preventDefault();
      const value = input ? input.value.trim() : "";
      if (!value) return;
      try {
        const hash = await sha256Hex(value);
        if (hash === GATE_HASH) {
          unlock();
        } else {
          reject();
        }
      } catch (err) {
        console.error("Gate hash error:", err);
        reject();
      }
    });
  }
})();

// ============================================================
// THEME TOGGLE — persists in localStorage
// ============================================================
(function() {
  const STORAGE_KEY = "hako-theme";
  const root = document.documentElement;

  const stored = localStorage.getItem(STORAGE_KEY);
  if (stored === "dark" || stored === "light") {
    root.setAttribute("data-theme", stored);
  } else {
    root.setAttribute("data-theme", "light");
  }

  const toggle = document.querySelector(".theme-toggle");
  if (toggle) {
    toggle.addEventListener("click", () => {
      const current = root.getAttribute("data-theme");
      const next = current === "dark" ? "light" : "dark";
      root.setAttribute("data-theme", next);
      localStorage.setItem(STORAGE_KEY, next);
    });
  }
})();

// ============================================================
// REVEAL ON SCROLL
// ============================================================
(function() {
  const reveals = document.querySelectorAll(".reveal");
  if (!reveals.length) return;

  const observer = new IntersectionObserver(
    (entries) => {
      entries.forEach((entry) => {
        if (entry.isIntersecting) {
          entry.target.classList.add("active");
          observer.unobserve(entry.target);
        }
      });
    },
    { threshold: 0.1, rootMargin: "0px 0px -60px 0px" }
  );

  reveals.forEach((el) => observer.observe(el));
})();

// ============================================================
// FAQ ACCORDION — keeps click-to-toggle behavior + ARIA
// ============================================================
(function() {
  const faqItems = document.querySelectorAll(".faq-item");
  faqItems.forEach((item) => {
    const button = item.querySelector(".faq-question");
    if (!button) return;
    button.addEventListener("click", () => {
      const wasActive = item.classList.contains("active");
      faqItems.forEach((other) => {
        other.classList.remove("active");
        const btn = other.querySelector(".faq-question");
        if (btn) btn.setAttribute("aria-expanded", "false");
      });
      if (!wasActive) {
        item.classList.add("active");
        button.setAttribute("aria-expanded", "true");
      }
    });
  });
})();

// ============================================================
// MOBILE NAV
// ============================================================
(function() {
  const btn = document.querySelector(".mobile-menu-btn");
  const nav = document.querySelector(".mobile-nav");
  if (!btn || !nav) return;

  btn.addEventListener("click", (e) => {
    e.stopPropagation();
    nav.classList.toggle("active");
  });

  nav.querySelectorAll("a").forEach((link) => {
    link.addEventListener("click", () => nav.classList.remove("active"));
  });

  document.addEventListener("click", (e) => {
    if (!nav.contains(e.target) && !btn.contains(e.target)) {
      nav.classList.remove("active");
    }
  });

  document.addEventListener("keydown", (e) => {
    if (e.key === "Escape") nav.classList.remove("active");
  });
})();

// ============================================================
// SCROLLED NAV STATE
// ============================================================
(function() {
  const nav = document.querySelector(".navbar");
  if (!nav) return;

  const onScroll = () => {
    if (window.scrollY > 12) {
      nav.classList.add("scrolled");
    } else {
      nav.classList.remove("scrolled");
    }
  };
  onScroll();
  window.addEventListener("scroll", onScroll, { passive: true });
})();

// ============================================================
// NOTIFY FORM
// ============================================================
(function() {
  const form = document.getElementById("notifyForm");
  if (!form) return;

  form.addEventListener("submit", async (e) => {
    e.preventDefault();

    const button = form.querySelector("button[type='submit']");
    const input = form.querySelector("input[type='email']");
    const email = input ? input.value.trim() : "";

    if (button) {
      button.disabled = true;
      button.textContent = T("notify.sending", "Sending…");
    }

    const formData = new FormData(form);
    const payload = Object.fromEntries(formData);

    try {
      const response = await fetch("https://api.web3forms.com/submit", {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
          "Accept": "application/json",
        },
        body: JSON.stringify(payload),
      });

      const result = await response.json();

      if (result.success) {
        showConfirmation(form, email);
      } else {
        showError(form, button, T("error.generic", "Something went wrong. Please try again."));
      }
    } catch (err) {
      showError(form, button, T("notify.offline", "Couldn't reach the server. Please try again later."));
      console.error("Web3Forms error:", err);
    }
  });

  function showConfirmation(form, email) {
    form.style.display = "none";
    const message = document.createElement("p");
    message.style.cssText =
      "color: var(--accent); font-weight: 500; font-size: 17px; margin-top: 8px; line-height: 1.6;";
    message.textContent = email
      ? T("notify.ok_email", "You're on the list. I'll write to {email} when it drops.", { email })
      : T("notify.ok", "You're on the list. I'll write to you when it drops.");
    form.insertAdjacentElement("afterend", message);
  }

  function showError(form, button, msg) {
    if (button) {
      button.disabled = false;
      button.textContent = T("notify.button", "Notify me");
    }
    const existing = form.parentElement.querySelector(".notify-error");
    if (existing) existing.remove();
    const err = document.createElement("p");
    err.className = "notify-error";
    err.style.cssText =
      "color: var(--accent); font-size: 13px; margin-top: 12px;";
    err.textContent = msg;
    form.insertAdjacentElement("afterend", err);
  }
})();

// ============================================================
// SIGNUP COUNTER
// ============================================================
(function() {
  const counter = document.getElementById("signupCounter");
  const numberEl = document.getElementById("counterNumber");
  if (!counter || !numberEl) return;

  const target = window.SIGNUP_COUNT || 0;
  const minToShow = window.MIN_TO_SHOW || 0;

  if (target < minToShow) {
    counter.style.display = "none";
    return;
  }

  counter.style.display = "";
  counter.setAttribute("aria-hidden", "false");

  const reducedMotion = window.matchMedia("(prefers-reduced-motion: reduce)").matches;
  if (reducedMotion) {
    numberEl.textContent = target.toLocaleString();
    counter.classList.add("active");
    return;
  }

  function easeInOut(t) {
    return t < 0.5 ? 4 * t * t * t : 1 - Math.pow(-2 * t + 2, 3) / 2;
  }

  function runCounter() {
    const duration = 1800;
    const start = performance.now();

    function frame(now) {
      const elapsed = now - start;
      const progress = Math.min(elapsed / duration, 1);
      const eased = easeInOut(progress);
      const value = Math.round(eased * target);
      numberEl.textContent = value.toLocaleString();
      if (progress < 1) {
        requestAnimationFrame(frame);
      } else {
        numberEl.textContent = target.toLocaleString();
      }
    }
    requestAnimationFrame(frame);
  }

  const observer = new IntersectionObserver(
    (entries) => {
      entries.forEach((entry) => {
        if (entry.isIntersecting) {
          counter.classList.add("active");
          runCounter();
          observer.unobserve(counter);
        }
      });
    },
    { threshold: 0.5 }
  );
  observer.observe(counter);
})();

// ============================================================
// FOUNDER EDITION — price, units left, pre-order button.
// Configured in <head> (FOUNDER_PRICE, FOUNDER_TOTAL,
// FOUNDER_SOLD, PREORDER_URL).
// ============================================================
(function() {
  const price = window.FOUNDER_PRICE || "$279";
  document.querySelectorAll("[data-founder-price]").forEach((el) => {
    el.textContent = price;
  });

  const total = Number(window.FOUNDER_TOTAL) || 25;
  const sold = Math.min(Math.max(Number(window.FOUNDER_SOLD) || 0, 0), total);
  const left = total - sold;

  const leftEl = document.getElementById("founderLeft");
  const totalEl = document.getElementById("founderTotal");
  const fill = document.getElementById("founderBarFill");
  if (leftEl) leftEl.textContent = left;
  if (totalEl) totalEl.textContent = total;
  if (fill) fill.style.width = `${(sold / total) * 100}%`;

  const cta = document.getElementById("founderCta");
  if (!cta) return;
  if (window.SHOP_API) {
    liveShop(cta, price);
    return;
  }
  if (left === 0) {
    cta.textContent = T("shop.sold_out_cta", "Sold out · join the Kickstarter waitlist");
    cta.setAttribute("href", "#notify");
  } else if (window.PREORDER_URL) {
    cta.textContent = T("shop.preorder", "Pre-order · {price}", { price });
    cta.setAttribute("href", window.PREORDER_URL);
    cta.setAttribute("rel", "noopener");
  }
})();

// ============================================================
// SOCIAL LINKS — set from window.LINKS; hidden while empty.
// ============================================================
(function() {
  const links = window.LINKS || {};
  document.querySelectorAll("[data-link]").forEach((el) => {
    const url = links[el.dataset.link];
    if (url) {
      el.setAttribute("href", url);
    } else {
      el.style.display = "none";
    }
  });
})();

// ============================================================
// LIVE SHOP — talks to the shop Worker (window.SHOP_API):
// live counter, country picker with shipping, Stripe checkout.
// ============================================================
async function liveShop(cta, price) {
  const api = window.SHOP_API.replace(/\/$/, "");
  const picker = document.getElementById("founderCountry");
  const select = document.getElementById("countrySelect");
  const shipEl = document.getElementById("founderShip");
  const errorEl = document.getElementById("founderError");
  const lang = document.documentElement.lang || "en";

  function setCounter(total, sold) {
    const left = Math.max(total - sold, 0);
    const leftEl = document.getElementById("founderLeft");
    const totalEl = document.getElementById("founderTotal");
    const fill = document.getElementById("founderBarFill");
    if (leftEl) leftEl.textContent = left;
    if (totalEl) totalEl.textContent = total;
    if (fill) fill.style.width = `${(sold / total) * 100}%`;
  }

  let status;
  try {
    status = await (await fetch(`${api}/status`)).json();
  } catch (e) {
    return; // keep the static fallback
  }
  setCounter(status.total, status.sold);

  if (status.left === 0) {
    cta.textContent = T("shop.sold_out_cta", "Sold out · join the Kickstarter waitlist");
    cta.setAttribute("href", "#notify");
    return;
  }

  // Country picker, names in the visitor's language, guessed from the browser
  let names;
  try {
    names = new Intl.DisplayNames([lang, navigator.language || lang, "en"], { type: "region" });
  } catch (e) {
    names = { of: (c) => c };
  }
  const options = status.countries
    .map((code) => ({ code, name: names.of(code) || code }))
    .sort((a, b) => a.name.localeCompare(b.name));
  select.innerHTML = options.map((o) => `<option value="${o.code}">${o.name}</option>`).join("");
  const guess = (navigator.language || "").split("-")[1];
  select.value = status.countries.includes(guess) ? guess : "US";

  function money(cents) {
    return new Intl.NumberFormat(navigator.language || "en", { style: "currency", currency: "USD" })
      .format(cents / 100);
  }
  function showShipping() {
    const cents = status.shipping[select.value] ?? status.shipping["*"] ?? 0;
    shipEl.textContent = T("shop.shipping", "+ {amount} shipping", { amount: money(cents) });
  }
  select.addEventListener("change", showShipping);
  showShipping();
  // Shown before pre-orders open too, so people can see what shipping costs
  picker.hidden = false;
  if (!status.open) return; // the button keeps "Pre-orders open spring 2027"

  cta.textContent = T("shop.preorder", "Pre-order · {price}", { price });
  cta.setAttribute("href", "#");
  cta.addEventListener("click", async (e) => {
    e.preventDefault();
    errorEl.textContent = "";
    cta.classList.add("is-busy");
    cta.textContent = T("shop.opening", "Opening checkout…");
    try {
      const r = await fetch(`${api}/checkout`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ country: select.value }),
      });
      const data = await r.json();
      if (data.url) {
        window.location.href = data.url;
        return;
      }
      errorEl.textContent = {
        all_held: T("shop.all_held", "The last boxes are in other people's checkouts right now. Try again in 30 minutes."),
        sold_out: T("shop.sold_out", "Sold out — join the waitlist for the Kickstarter."),
        not_open: T("shop.not_open", "Pre-orders aren't open yet."),
      }[data.error] || T("error.generic", "Something went wrong. Please try again.");
    } catch (err) {
      errorEl.textContent = T("shop.offline", "Couldn't reach checkout. Please try again.");
    }
    cta.classList.remove("is-busy");
    cta.textContent = T("shop.preorder", "Pre-order · {price}", { price });
  });
}

// ============================================================
// LANGUAGE SWITCHER — remember the choice so the first-visit
// redirect (in <head>) never overrides it.
// ============================================================
(function() {
  const current = document.documentElement.lang || "en";
  document.querySelectorAll(".lang-switch a").forEach((a) => {
    if (a.dataset.lang === current) a.setAttribute("aria-current", "page");
    a.addEventListener("click", (e) => {
      try { localStorage.setItem("hako-lang", a.dataset.lang); } catch (err) {}
      // keep the visitor's place on the page
      if (location.hash) {
        e.preventDefault();
        location.href = a.getAttribute("href") + location.hash;
      }
    });
  });
})();
