#!/usr/bin/env python3
"""
build-i18n.py — generate the Japanese and German pages (ja/index.html,
de/index.html) from index.html and tools/i18n.json.

    python3 tools/build-i18n.py           # write the pages
    python3 tools/build-i18n.py --check   # fail if they're out of date (CI)

Separate pages (not text swapped in by JavaScript) so link previews on
LINE, X, Discord etc. show the right language, and search engines index each.
Any English text in i18n.json that's no longer on the page is reported, so
translations can't go stale silently.
"""
from __future__ import annotations

import argparse
import html
import json
import re
import sys
from pathlib import Path

SITE = Path(__file__).resolve().parent.parent
LANGS = ["ja", "de"]
BANNER = "<!-- GENERATED by tools/build-i18n.py from index.html + tools/i18n.json. Don't edit; edit those and re-run. -->\n"


def text_pattern(en: str) -> re.Pattern:
    """Match `en` as a whole text run between two tags; any whitespace in
    `en` matches any whitespace (line breaks in the source don't matter)."""
    parts = [re.escape(p) for p in en.split()]
    body = r"\s+".join(parts)
    # Allow whitespace that sits between tags (e.g. "<br/> that") to be absent or present
    body = body.replace(r">\s+", r">\s*").replace(r"\s+<", r"\s*<")
    return re.compile(r"(?<=>)(\s*)" + body + r"(\s*)(?=<)")


def relative_to_parent(page: str) -> str:
    """The language pages live one folder down: fix relative links."""
    return re.sub(r'(\b(?:src|href)=")(?!https?:|#|mailto:|/|data:|\.\./)([^"]+")', r"\1../\2", page)


def build(lang: str, source: str, tr: dict) -> tuple[str, list[str]]:
    missing = []
    page = source

    head = tr["head"][lang]
    page = page.replace('<html lang="en"', f'<html lang="{lang}"', 1)
    page = re.sub(r"<title>.*?</title>", f"<title>{html.escape(head['title'])}</title>", page, count=1)
    page = re.sub(r'(<meta name="description" content=")[^"]*', lambda m: m.group(1) + html.escape(head["description"], quote=True), page, count=1)
    page = re.sub(r'(<meta property="og:description" content=")[^"]*', lambda m: m.group(1) + html.escape(head["og_description"], quote=True), page, count=1)
    page = page.replace('content="https://www.hakoshop.com/"', f'content="https://www.hakoshop.com/{lang}/"', 1)
    page = page.replace('assets/images/og.png"', f'assets/images/og-{lang}.png"', 1)
    page = page.replace('<meta property="og:locale" content="en_US" />', f'<meta property="og:locale" content="{head["locale"]}" />', 1)
    page = page.replace('<link rel="canonical" href="https://www.hakoshop.com/" />', f'<link rel="canonical" href="https://www.hakoshop.com/{lang}/" />', 1)

    for entry in tr["attr"]:
        if entry["en"] not in page:
            missing.append(f"attr: {entry['en']}")
        page = page.replace(entry["en"], entry[lang])

    # Longest first, so "Founder Edition or the Kickstarter run?" wins over "Founder Edition"
    for entry in sorted(tr["text"], key=lambda e: -len(e["en"])):
        pat = text_pattern(entry["en"])
        page, n = pat.subn(lambda m, t=entry[lang]: m.group(1) + t + m.group(2), page)
        if n == 0:
            missing.append(f"text: {entry['en'][:70]}")

    strings = json.dumps(tr["strings"][lang], ensure_ascii=False, indent=2)
    page = page.replace("</head>", f"  <script>\n    window.HAKO_STRINGS = {strings};\n  </script>\n</head>", 1)
    page = relative_to_parent(page)
    page = page.replace("<!DOCTYPE html>\n", "<!DOCTYPE html>\n" + BANNER, 1)
    return page, missing


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true", help="exit 1 if the pages are out of date")
    args = ap.parse_args()

    source = (SITE / "index.html").read_text(encoding="utf-8")
    tr = json.loads((SITE / "tools/i18n.json").read_text(encoding="utf-8"))
    stale = False
    for lang in LANGS:
        page, missing = build(lang, source, tr)
        for m in missing:
            print(f"[{lang}] not found in index.html (update tools/i18n.json): {m}", file=sys.stderr)
        out = SITE / lang / "index.html"
        if args.check:
            if not out.exists() or out.read_text(encoding="utf-8") != page:
                print(f"{out.relative_to(SITE)} is out of date: run python3 tools/build-i18n.py", file=sys.stderr)
                stale = True
        else:
            out.parent.mkdir(exist_ok=True)
            out.write_text(page, encoding="utf-8")
            print(f"wrote {out.relative_to(SITE)}" + (f" ({len(missing)} untranslated)" if missing else ""))
    sys.exit(1 if stale else 0)


if __name__ == "__main__":
    main()
